title: Oliver Hannaoui
email: ozh att stat att cmu dot edu
description: >- 
  Placeholder description
baseurl: "" 
url: "https://hanna-oui.github.io"

twitter_username: placeholder
github_username:  hanna-oui

plugins:
  - jekyll-feed